// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using POC_EF_Core_3;

namespace POC_EF_Core_3.Migrations
{
    [DbContext(typeof(PocDbContext))]
    [Migration("20190928233837_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("POC_EF_Core_3.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<short>("Amount")
                        .HasColumnType("smallint");

                    b.Property<long?>("BoundCharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<short>("Design")
                        .HasColumnType("smallint");

                    b.Property<int>("DurabilityPoint")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ItemDeleteTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short>("ItemVNum")
                        .HasColumnType("smallint");

                    b.Property<short>("Rare")
                        .HasColumnType("smallint");

                    b.Property<byte>("Upgrade")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("ItemInstance");
                });
#pragma warning restore 612, 618
        }
    }
}
